# Generated by Django 4.2.5 on 2023-09-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('total_pages', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
