# Generated by Django 4.2.5 on 2023-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_published',
            field=models.DateField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
