# Generated by Django 4.2.5 on 2023-09-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_published',
            field=models.DateField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
